/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.cernaj.test.mapstruct;

import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;

import static org.junit.jupiter.api.Assertions.assertEquals;

class EmployeeMapperTest {

    private final EmployeeMapper mapper = Mappers.getMapper( EmployeeMapper.class );

    @Test
    void noPrivileges() {
        Employee source = new Employee( "John Doe", "21 Jump Street", "50000" );
        EmployeeDTO expected = new EmployeeDTO( "John Doe", "<confidential>", "<confidential>" );

        EmployeeDTO target = mapper.toDto( source, null );

        assertEquals( expected, target );
    }

    @Test
    void companyPrivileges() {
        Employee source = new Employee( "John Doe", "21 Jump Street", "50000" );
        EmployeeDTO expected = new EmployeeDTO( "John Doe", "21 Jump Street", "<confidential>" );

        EmployeeDTO target = mapper.toDto( source, "company" );

        assertEquals( expected, target );
    }

    @Test
    void managementPrivileges() {
        Employee source = new Employee( "John Doe", "21 Jump Street", "50000" );
        EmployeeDTO expected = new EmployeeDTO( "John Doe", "21 Jump Street", "50000" );

        EmployeeDTO target = mapper.toDto( source, "management" );

        assertEquals( expected, target );
    }
}
