/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.cernaj.test.mapstruct;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class MapperTest {
    @Test
    void someLibraryMethodReturnsTrue() {
//        var mapper = Mappers.getMapper(BeanMapper.class);
        var mapper = new BeanMapperImplPoc();

        var source = new SourceBean("Hello", "World");
        var expected = new TargetBean("HELLO", "dlroW");

        var target = mapper.toTarget(source);

        assertEquals(expected, target);
    }
}
